

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kotlin?characterEncoding=UTF-8
    username: root
    password: bing4470
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
#  mvc:
#    view:
#      prefix: /static
#      suffix: .html
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  freemarker:
    content-type: application/json
logging:
  level: debug

app:
  jwt:
    secret: qwertyuiop

security:
#  myUser:
#    name: admin
#    password: admin

